### PR TITLE
Fixed SQLite issue

### PR DESCRIPTION
**Pull request by dutok**

### CODE REVIEW

**Comment by PEMapModder** [comment]
@dutok this is a minor change, so you can commit directly. Only make pulls for large and unstable commits :)

**Comment by dutok** [comment]
@PEMapModder I'm not a member of this repository so I can't.

**Comment by PEMapModder** [comment]
Oops I forgot @iksaku transferred it.

**Comment by iksaku** [comment]
@PEMapModder I told you that only HealthBar and EssentialsPE are part of the organization xD MagicClock and MoreHealth are mine :P 

-----Mensaje original-----
De: PEMapModder
Enviado: 22/08/2014 09:35 p.m.
Para: iksaku/MoreHealth
CC: Jorge González
Asunto: Re: [MoreHealth] Fixed SQLite issue (#3)

Oops I forgot @iksaku transferred it.

**Pull request merged**
